title: Let's upgrade
description: Python essentials
template:
  repo: let's-upgrade-template
  name: let's-upgrade
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
